name: bookstore
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  logger: ^2.4.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/core/assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lora
      fonts:
        - asset: lib/core/fonts/Lora-Regular.ttf
        - asset: lib/core/fonts/Lora-Bold.ttf
          weight: 700
        - asset: lib/core/fonts/Lora-Medium.ttf
          weight: 500
        - asset: lib/core/fonts/Lora-SemiBold.ttf
          weight: 600
        - asset: lib/core/fonts/Lora-Italic.ttf
          style: italic
        - asset: lib/core/fonts/Lora-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/core/fonts/Lora-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/core/fonts/Lora-SemiBoldItalic.ttf
          weight: 600
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  
    