name: bookstore
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/core/assets/
  
  fonts:
    - family: Lora
      fonts:
        - asset: lib/core/fonts/Lora-Regular.ttf
        - asset: lib/core/fonts/Lora-Bold.ttf
          weight: 700
  
    