name: bookstore
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  logger: ^2.4.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/core/assets/
  
  fonts:
    - family: Lora
      fonts:
        - asset: lib/core/fonts/Lora-Regular.ttf
        - asset: lib/core/fonts/Lora-Bold.ttf
          weight: 700
  
    